openapi: 3.0.0
info:
  title: RAG Service API
  version: 1.0.0
paths:
  /ask:
    post:
      summary: Ask a question
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
      responses:
        '200':
          description: An answer to the question